/*
##
##	Enhancer for YouTube™ | Firefox Add-on
##	======================================
##
##	Author: Maxime RF <https://www.mrfdev.com>
##
##	This file is protected by copyright laws and international copyright
##	treaties, as well as other intellectual property laws and treaties.
##
##	All rights not expressly granted to you are retained by the author.
##	Read the license.txt file for more details.
##
##	If it's not enough clear for you Baris Derin, you have no rights to use my work,
##	neither as-is nor modified! Being an AMO Editor doesn't give you that right!
##	Improve your coding logic instead of using others work!
##
##	© MRFDEV.com - All Rights Reserved
##
*/
(function(a){if(!window.EnhancerForYouTube){var ya=function(a){var f;"undefined"===typeof a&&(f=JSON.parse(localStorage.getItem("enhancer-for-youtube")||'{"customtheme":""}'));localStorage.setItem("enhancer-for-youtube",JSON.stringify({customtheme:f?f.customtheme:a,theme:b.theme,polymer:!0}))},la=function(){if(k){for(var a=k.querySelectorAll("li"),h=a.length-1;0<=h;h--)a[h].classList[0<=b.toolbarbuttons.indexOf(a[h].dataset.name)?"remove":"add"]("hidden");k.querySelector('li[data-name="message"]').classList[b.message?
"remove":"add"]("hidden");""!==b.toolbarbuttons||b.message?(v.classList.remove("hidden"),za()):v.classList.add("hidden")}},Pa=function(){ca();if(0===D[0].children.length){var b=p;D.slider({animate:"slow",range:!0,min:0,max:H,values:[p,w],start:function(a,c){b=p},slide:function(b,c){p=c.values[0];w=c.values[1];ca()},stop:function(a,c){p===H?(p=H-1,ma(),ca()):w===p&&(w=p+1,ma(),ca());b!==p&&d.seekTo(p)}})}else ma();D.show();v.classList.add("extended")},ma=function(){D.slider("values",[p,w])},ca=function(){Aa[0].textContent=
na(p)+" / "+na(w)},Ba=function(b){if(b.classList.contains("active"))clearInterval(V),b.classList.remove("active"),D.hide(),v.classList.remove("extended");else{b.classList.add("active");0===$("#enhancer-for-youtube-slider",k).length&&(D=$("<div />").attr("id","enhancer-for-youtube-slider").appendTo(k),Aa=$("<div />").addClass("start-end").appendTo(k));H=p=w=!1;var f=0,c=0<a.location.href.indexOf("list=");V=setInterval(function(){try{d&&"function"===typeof d.getPlayerState?H?!c&&d.getCurrentTime()>=
w?d.seekTo(p):c||0!==d.getPlayerState()?(c&&H===w&&2>H-d.getCurrentTime()||c&&H!==w&&d.getCurrentTime()>=w)&&d.seekTo(p):d.playVideo():(H=w=parseInt(d.getDuration(),10),p=0,"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&(p=ytplayer.config.args.start?parseInt(ytplayer.config.args.start,10):0,w=ytplayer.config.args.end?parseInt(ytplayer.config.args.end,10):w),f=0,Pa()):(f++,N())}catch(e){15<f&&clearInterval(V),d=!1}},1E3)}},na=function(b){b=Number(b);var a=Math.floor(b/3600),
c=Math.floor(b%3600/60);b=Math.floor(b%3600%60);return(0<a?a+":":"")+(0<c?(0<a&&10>c?"0":"")+c+":":"0:")+(10>b?"0":"")+b},qa=function(){a.body.classList.remove("enhancer-for-youtube-pinned-player");oa||pa();a.body.classList.contains("viewport")&&(a.body.classList.remove("viewport"),a.body.classList.add("_viewport_"));window.scrollTo(0,0);a.body.classList.add("enhancer-for-youtube-cinema-mode");b.cinemamodewideplayer&&!a.body.classList.contains("enhancer-for-youtube-wide-player")&&E("large");0<=b.autofocusevents.indexOf("cinema")&&
q()},da=function(){a.body.classList.remove("enhancer-for-youtube-cinema-mode");!b.wideplayer&&b.cinemamodewideplayer?E("default"):a.body.classList.contains("_viewport_")&&(a.body.classList.remove("_viewport_"),a.body.classList.add("viewport"));0<=b.autofocusevents.indexOf("cinema")&&q()},Ca=function(a){if(b.controlvolumealtkey&&a.altKey||!b.controlvolumealtkey&&!a.ctrlKey){a.preventDefault();try{var f=d.getVolume();0<a.deltaY?(f-=b.volumevariation,0>f&&(f=0)):(f+=b.volumevariation,100<f&&(f=100),
d.isMuted()&&d.unMute());d.setVolume(f);L.textContent=f;ra();b.defaultvolume&&(b.volume=f);var c=(new Date).getTime();a=0<f?"false":"true";localStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+f+',\\"muted\\":'+a+'}","expiration":'+(c+2592E6)+',"creation":'+c+"}";sessionStorage["yt-player-volume"]='{"data":"{\\"volume\\":'+f+',\\"muted\\":'+a+'}","creation":'+c+"}"}catch(e){}}},Q=function(){var a=[b.quality1,b.quality2,b.quality3,b.quality4],h=setInterval(function(){try{if(d&&"function"===typeof d.getPlayerState||
("video"===B?N():sa()),-1!==d.getPlayerState()){for(var b=0,f=!1,l,g=d.getAvailableQualityLevels();b<a.length&&!f;b++)for(var k in g)if(a[b]===g[k]){f=a[b];break}l=f?f:"auto";l!==d.getPlaybackQuality()?F||(F=!0,d.hasAttribute("flashvars")?(d.pauseVideo(),d.setPlaybackQuality(l),d.playVideo()):d.setPlaybackQuality(l)):l===d.getPlaybackQuality()&&(F=!0,clearInterval(h),clearTimeout(c))}}catch(ea){d=!1}},500),c=setTimeout(function(){clearInterval(h)},3E4)},aa=function(f){d||N();if(d&&d.hasAttribute("flashvars")){clearInterval(V);
clearInterval(R);k&&D&&(k.querySelector("i.loop").parentNode.classList.remove("active"),D.slider("destroy"));var h="ad_module ad2_module ad3_module ad_channel_code_instream ad_channel_code_overlay ad_device ad_eurl ad_flags ad_host ad_host_tier ad_logging_flag ad_preroll ad_slots ad_tag ad_type ad_video_pub_id adsense_video_doc_id advideo aftv afv afv_ad_tag afv_ad_tag_restricted_to_instream afv_invideo_ad_tag afv_inslate_ad_tag afv_instream_max afv_video_min_cpm allow_html5_ads allowed_ads apply_fade_on_midrolls as_launched_in_country baseUrl cafe_experiment_id cc_asr enabled_engage_types excluded_ads dynamic_allocation_ad_tag max_dynamic_allocation_ad_tag_length max_ad_duration ppv_remarketing_url prefetch_ad_live_stream pyv_ad_channel remarketing_url rmktEnabled show_pyv_in_related use_meta_ad_player".split(" "),
c=function(b){for(var a=h.length-1;0<=a;a--)if(b===h[a])return!0;return!1},e=d.getAttribute("flashvars"),W=d.cloneNode(!0);e=e.split("&");for(var l=[],I,n,ea=0;ea<e.length;ea++)I=e[ea].split("="),n=I[0],I=I[1],c(n)||l.push(n+"="+I);c=l.join("&");0>c.indexOf("enablejsapi")&&(c+="&enablejsapi=1");0>c.indexOf("iv_load_policy")&&(c+="&iv_load_policy=1");0>c.indexOf("autoplay")&&(c+="&autoplay=1");b.removeannotations&&(c=c.replace("iv_load_policy=1","iv_load_policy=3"));W.setAttribute("flashvars",c);m.textContent=
"";m.appendChild(W);ta(m);F=!1;b.autopausevideos?X():b.selectquality&&Q()}else if(d){if(f||"function"===typeof d.getAdState&&1===d.getAdState()&&"function"===typeof d.getDuration){if(Y)return;try{Number.isFinite(g.duration)?3<d.getDuration()-g.duration&&(Y=!0,g.currentTime=g.duration-.5,Z(),b.overridespeeds?g.playbackRate=b.speed:d.setPlaybackRate(b.speed),b.autopausevideos&&X()):setTimeout(function(){aa(f)},50)}catch(Da){if(!g||(0<Da.message.indexOf("currentTime")||"IndexSizeError"===Da.message)&&
g!=a.querySelector("video.html5-main-video"))return}}else Z();0<=b.autofocusevents.indexOf("ads")&&q()}else setTimeout(function(){aa(f)},100)},Z=function(){d.classList.add("ads-removed")},ba=function(){try{"object"===typeof S&&(S.disconnect(),S=void 0);var a=d.querySelector("button.ytp-settings-button"),h=d.querySelector("div.ytp-settings-menu");if(!F&&a&&h){S=new MutationObserver(function(a){a.forEach(function(a){if(null!==a.addedNodes)for(var c=a.addedNodes.length-1;0<=c;c--)if("DIV"===a.addedNodes[c].nodeName&&
a.addedNodes[c].classList.contains("ytp-menuitem")&&/\d{3,4}[p,s]/.test(a.addedNodes[c].textContent))a.addedNodes[c].click();else if("DIV"===a.addedNodes[c].nodeName&&a.addedNodes[c].classList.contains("ytp-quality-menu")){c=0;var f=!1,e={"4320p60 8K":"highres","4320p50 8K":"highres","4320p48 8K":"highres","4320p 8K":"highres","4320s 8K":"highres","2880p60 5K":"hd2880","2880p50 5K":"hd2880","2880p48 5K":"hd2880","2880p 5K":"hd2880","2880s 5K":"hd2880","2160p60 4K":"hd2160","2160p50 4K":"hd2160","2160p48 4K":"hd2160",
"2160p 4K":"hd2160","2160s 4K":"hd2160","1440p60 HD":"hd1440","1440p50 HD":"hd1440","1440p48 HD":"hd1440","1440p HD":"hd1440","1440s HD":"hd1440","1080p60 HD":"hd1080","1080p50 HD":"hd1080","1080p48 HD":"hd1080","1080p HD":"hd1080","1080s HD":"hd1080","720p60 HD":"hd720","720p50 HD":"hd720","720p48 HD":"hd720","720p HD":"hd720","720s HD":"hd720","480p":"large","480s":"large","360p":"medium","360s":"medium","240p":"small","240s":"small","144p":"tiny","144s":"tiny"},d=a.addedNodes[c].querySelectorAll("div.ytp-menuitem");
0<d.length&&[b.quality1,b.quality2,b.quality3,b.quality4].forEach(function(a){if(!f){for(;c<d.length;c++)if(a===e[d[c].textContent]){d[c].click();f=!0;break}c=0}});f||d[0].click();F=!0;h.classList.remove("hidden");S.disconnect()}})});S.observe(h,{childList:!0,subtree:!0});for(var c=h.querySelectorAll("div.ytp-menuitem"),e,g=c.length-1;0<=g;g--)if(/\d{3,4}[p,s]/.test(c[g].textContent)){e=c[g];break}h.classList.add("hidden");setTimeout(function(){h.classList.remove("hidden")},2500);e?(a.click(),e.click()):
a.click()}else if(!F){var l=d.getAvailableQualityLevels();0<=l.indexOf(b.quality1)?d.setPlaybackQuality(b.quality1):0<=l.indexOf(b.quality2)?d.setPlaybackQuality(b.quality2):0<=l.indexOf(b.quality3)?d.setPlaybackQuality(b.quality3):0<=l.indexOf(b.quality4)&&d.setPlaybackQuality(b.quality4)}}catch(I){}},E=function(f){try{var d=a.body.classList.contains("enhancer-for-youtube-wide-player");t&&!G&&(G=t.classList.contains("watch-stage-mode")&&!a.body.classList.contains("enhancer-for-youtube-wide-player"));
if("large"===f||!f&&!d){oa||pa();var c=a.querySelector('.ytp-right-controls path[d="m 28,11 0,14 -20,0 0,-14 z m -18,2 16,0 0,10 -16,0 0,-10 z"]')||a.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');if(c)var e=c.parentNode.parentNode;if(G&&e){e.click();var g=setInterval(function(){!t.classList.contains("watch-non-stage-mode")||t.classList.contains("watch-wide")||t.classList.contains("watch-stage-mode")||(clearInterval(g),G=!0,Ea(e,"1"))},20)}else Ea(e,
G?"1":"0")}else if("default"===f||!f&&d){var l=a.querySelector('.ytp-right-controls path[d="m 26,13 0,10 -16,0 0,-10 z m -14,2 12,0 0,6 -12,0 0,-6 z"]');if(l)var k=l.parentNode.parentNode;k?k.click():k||G||(t.classList.add("watch-non-stage-mode"),t.classList.remove("watch-wide"),t.classList.remove("watch-stage-mode"));G||k||setTimeout(function(){window.postMessage({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:"0"},"*")},250);a.body.classList.remove("enhancer-for-youtube-wide-player",
"viewport","_viewport_");k&&G&&(g=setInterval(function(){!t.classList.contains("watch-non-stage-mode")||t.classList.contains("watch-wide")||t.classList.contains("watch-stage-mode")||(clearInterval(g),G=!1,k.click())},20))}}catch(Qa){}0<=b.autofocusevents.indexOf("size")&&q()},Ea=function(f,h){f?f.click():(t.classList.add("watch-wide"),t.classList.add("watch-stage-mode"),t.classList.remove("watch-non-stage-mode"));a.body.classList.add("enhancer-for-youtube-wide-player");b.wideplayerviewport&&fa&&(a.body.classList.contains("enhancer-for-youtube-cinema-mode")?
a.body.classList.add("_viewport_"):(a.body.classList.add("viewport"),setTimeout(function(){window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},80)));setTimeout(function(){window.postMessage({enhancerforyoutube:"set-cookie",url:a.location.href,name:"wide",value:h},"*")},250)},X=function(){if(b.ignoreplaylists&&0<a.location.href.indexOf("list=")||!b.pauseforegroundtab&&!ua&&!a.hidden)b.selectquality&&(n?Q():ba()),a.hidden||(O=!0);else{a.hidden||(O=!0);clearInterval(R);try{b.disablepreloading?
(d.stopVideo(),d.addEventListener("onStateChange",function W(a){if(1===a){d.removeEventListener("onStateChange",W);b.selectquality&&n&&Q();try{d[b.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",b.removeannotations?0:1),"undefined"!==typeof ytplayer&&ytplayer.config&&ytplayer.config.args&&ytplayer.config.args.start&&d.seekTo(parseInt(ytplayer.config.args.start,10))}catch(l){}}})):d.pauseVideo()}catch(c){var f,h=0;R=setInterval(function(){try{d&&
"function"===typeof d.getPlayerState||(h++,"video"===B?N():sa()),f=d.getPlayerState(),a.hidden?-1!==f&&b.disablepreloading?d.stopVideo():2===f||b.disablepreloading||d.pauseVideo():-1!==f&&5!==f&&b.pauseforegroundtab&&b.disablepreloading?d.stopVideo():2!==f&&b.pauseforegroundtab&&!b.disablepreloading?(-1!==f&&5!==f||d.playVideo(),3!==f&&d.pauseVideo()):clearInterval(R)}catch(e){200<h&&clearInterval(R),d=!1}},50)}q()}},Fa=function(a){if(a.ctrlKey&&!a.shiftKey&&"function"===typeof d.getPlayerState&&
0<d.getPlayerState()||"I"===a.target.nodeName){a.preventDefault();r=b.speed;try{b.overridespeeds?g.playbackRate=r:d.setPlaybackRate(r),"I"===a.target.nodeName?u.textContent=C.speed+" x"+r:(L.textContent="x"+r,ra())}catch(h){}0<=b.autofocusevents.indexOf("speed")&&q()}},ra=function(){L.setAttribute("style","display:block!important");clearTimeout(Ga);Ga=setTimeout(function(){L.setAttribute("style","display:none!important")},1500)},za=function(){v.style.marginLeft="-"+parseInt(window.getComputedStyle(k,
null).getPropertyValue("width"),10)/2+"px"},J=function(a,d){a.addEventListener("mouseenter",function(a){b.toolbartooltips&&(u.textContent=d,u.style.left=4+Math.floor(a.target.getBoundingClientRect().left)-parseInt(window.getComputedStyle(u,null).getPropertyValue("width"),10)/2+"px",u.classList.add("visible"))});a.addEventListener("mouseleave",function(){u.classList.remove("visible")})},Ra=function(){try{z.max=g.duration,z.value=g.currentTime}catch(f){}},Ha=function(a){if("I"===a.target.nodeName||
a.ctrlKey)if(a.preventDefault(),!n){try{if(b.overridespeeds){var f=g.playbackRate;0<a.deltaY?(f=parseFloat((f-b.speedvariation).toFixed(2)),0>=f&&(f=b.speedvariation),g.playbackRate=f):0>a.deltaY&&(f=parseFloat((f+b.speedvariation).toFixed(2)),g.playbackRate=f)}else{var c=d.getAvailablePlaybackRates();f=d.getPlaybackRate();var e=c.indexOf(f);0<a.deltaY&&0<e?(f=c[e-1],d.setPlaybackRate(f)):0>a.deltaY&&e<c.length-1&&(f=c[e+1],d.setPlaybackRate(f))}r=f;"I"===a.target.nodeName?u.textContent=C.speed+" x"+
f:(L.textContent="x"+f,ra())}catch(W){}0<=b.autofocusevents.indexOf("speed")&&q()}},Ia=function(a){if("I"===a.target.nodeName||a.ctrlKey&&a.shiftKey){a.preventDefault();try{var f=""===(g.style.filter?g.style.filter:g.style["-webkit-filter"])?!1:!0;g.style["-webkit-filter"]=f?"":b.filter;g.style.filter=f?"":b.filter;k.querySelector("i.filters").parentNode.classList[f?"remove":"add"]("active")}catch(c){}0<=b.autofocusevents.indexOf("filters")&&q()}},ta=function(b){b.querySelector("#enhancer-for-youtube-player-info")||
(a.querySelector("#enhancer-for-youtube-player-info")||(L=a.createElement("div"),L.id="enhancer-for-youtube-player-info"),b.appendChild(L))},Sa=function(){if(!v){x=a.createElement("div");v=a.createElement("div");k=a.createElement("div");u=a.createElement("div");var f=a.createDocumentFragment(),h=a.createElement("ul"),c=a.createElement("li"),e=a.createElement("i");x.id="enhancer-for-youtube-background";x.style.visibility="hidden";x.addEventListener("click",function(){da()});f.appendChild(x);v.id="enhancer-for-youtube-toolbar-wrapper";
k.id="enhancer-for-youtube-toolbar";u.id="enhancer-for-youtube-tooltip";f.appendChild(u);k.style.visibility="hidden";b.transparency&&k.classList.add("transparency");b.slideeffect&&k.classList.add("slide-effect");c.dataset.name=e.className="message";c.appendChild(e);e=a.createElement("i");e.className="badge";c.appendChild(e);c.addEventListener("click",function(){window.postMessage({enhancerforyoutube:"show-message"},"*")});J(c,C.message);h.appendChild(c);c=a.createElement("li");e=a.createElement("i");
c.dataset.name=e.className="clean";c.appendChild(e);c.addEventListener("click",function(){va=!0;Y=!1;aa()});c.addEventListener("contextmenu",function(a){a.preventDefault();d||N();try{var c=d.getAttribute("annotations-module-loaded");d["1"===c?"unloadModule":"loadModule"]("annotations_module");d.setAttribute("annotations-module-loaded","1"===c?0:1);0<=b.autofocusevents.indexOf("annotations")&&q()}catch(I){}return!1});J(c,C.remove_ads);h.appendChild(c);c=a.createElement("li");e=a.createElement("i");
c.dataset.name=e.className="cinema";c.appendChild(e);c.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-cinema-mode")?da():qa()});J(c,C.cinema_mode);h.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="resize";c.appendChild(e);c.addEventListener("click",function(){a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-pinned-player")||(a.body.classList.contains("enhancer-for-youtube-pinned-player")&&
(a.body.classList.remove("enhancer-for-youtube-pinned-player"),window.scrollTo(0,0)),E())});c.addEventListener("contextmenu",function(a){a.preventDefault();try{window.scrollTo(window.scrollX,m.getBoundingClientRect().top+window.scrollY)}catch(l){}return!1});J(c,C.resize_player);h.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="detach";c.appendChild(e);c.addEventListener("click",function(){var b=a.location.href.match(/v=(.+)&?/)[1]+"?autoplay=1",c=a.location.href.match(/list=(.+)&?/);
c&&(b+="&list="+c[1]);try{d.pauseVideo();var f=d.getCurrentTime();f&&(b+="&start="+parseInt(f,10))}catch(Qa){}window.postMessage({enhancerforyoutube:"detach",params:b},"*")});J(c,C.detach_player);h.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="loop";c.appendChild(e);c.addEventListener("click",function(){if(Ja)Ba(this);else{Ja=!0;y=a.createElement("link");y.rel="stylesheet";y.href=P+"/vendor/jquery/jquery-ui.min.css";a.head.appendChild(y);var c=this,f=a.createElement("script");
f.src=P+"/vendor/jquery/jquery-3.3.1.min.js";f.onload=function(){f=a.createElement("script");f.src=P+"/vendor/jquery/jquery-ui.min.js";f.onload=function(){Ba(c)};a.head.appendChild(f)};a.head.appendChild(f)}0<=b.autofocusevents.indexOf("loop")&&q()});J(c,C.loop_video);h.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="speed";c.appendChild(e);n&&c.classList.add("not-allowed");c.addEventListener("click",Fa);c.addEventListener("wheel",Ha);c.addEventListener("mouseenter",
function(a){if(b.toolbartooltips){var c="";try{c=" x"+g.playbackRate}catch(I){}u.textContent=C.speed+c;u.style.left=4+Math.floor(a.target.getBoundingClientRect().left)-parseInt(window.getComputedStyle(u,null).getPropertyValue("width"),10)/2+"px";u.classList.add("visible")}});c.addEventListener("mouseleave",function(){u.classList.remove("visible")});h.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="filters";c.appendChild(e);n&&c.classList.add("not-allowed");
c.addEventListener("click",Ia);c.addEventListener("contextmenu",function(b){b.preventDefault();this.classList.contains("not-allowed")||(this.hasAttribute("ui")?a.querySelector("#enhancer-for-youtube-filters").classList.toggle("hidden"):window.postMessage({enhancerforyoutube:"filters"},"*"));return!1});J(c,C.filters);h.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="script";c.appendChild(e);c.addEventListener("click",function(){q();window.postMessage({enhancerforyoutube:"custom-script"},
"*")});J(c,C.custom_script);h.appendChild(c);c=a.createElement("li");e=a.createElement("i");c.dataset.name=e.className="options";c.appendChild(e);c.addEventListener("click",function(){q();window.postMessage({enhancerforyoutube:"show-options"},"*")});J(c,C.options);h.appendChild(c);k.appendChild(h);v.appendChild(k);f.appendChild(v);z=a.createElement("progress");z.id="enhancer-for-youtube-progress";z.max=1;z.value=0;z.addEventListener("click",function(a){g&&(g.currentTime=Math.floor((a.pageX-this.offsetLeft)*
this.max/this.offsetWidth));q()});z.addEventListener("mouseenter",function(){M.classList.add("visible")});z.addEventListener("mouseleave",function(){M.classList.remove("visible")});z.addEventListener("mousemove",function(a){g&&(M.textContent=na(Math.floor((a.pageX-this.offsetLeft)*this.max/this.offsetWidth)),M.style.left=a.pageX-parseInt(window.getComputedStyle(M,null).getPropertyValue("width"),10)/2-6+"px")});f.appendChild(z);M=a.createElement("div");M.id="enhancer-for-youtube-progress-tooltip";
f.appendChild(M);h=a.createElement("div");h.id="enhancer-for-youtube-unpin-player";h.addEventListener("click",function(){a.body.classList.remove("enhancer-for-youtube-pinned-player")});f.appendChild(h);a.body.appendChild(f);setTimeout(function(){la();za();x.style.visibility="";k.style.visibility=""},500);(new MutationObserver(function(b){b.forEach(function(b){try{!b.target.classList.contains("watch-non-stage-mode")||b.target.classList.contains("watch-wide")||b.target.classList.contains("watch-stage-mode")||
(a.body.classList.remove("enhancer-for-youtube-wide-player"),G=!1)}catch(I){}})})).observe(t,{attributes:!0,attributeFilter:["class"]})}},pa=function(){var b=a.documentElement.clientWidth,d=a.documentElement.clientHeight,c=a.querySelector("#masthead-positioner");c=c?parseInt(window.getComputedStyle(c,null).getPropertyValue("height"),10):50;var e=k?parseInt(window.getComputedStyle(k,null).getPropertyValue("height"),10)+1:30;var g=656>=b?240:1720<=b&&980<=d?720:1294<=b&&630<=d?480:360;if(parseInt(16/
9*(d-c-e),10)>b){c=b-4;e=parseInt(c/(16/9),10);var l=e-g;var m=240===g?0:g;var n=l;b=c;d=e;fa=!1}else e=parseInt(d-c-e,10),c=parseInt(16/9*e,10),l=e-g+(480===g?120:0),m=240===g?0:360,n=d-m,window.screen.height===d?(b-=4,d=parseInt(b/(16/9),10)):b=parseInt(16/9*d,10),fa=!0;var p=240===g?0:g;g=parseInt(c/2,10);var r=parseInt(b/2,10);var q=a.createElement("style");q.type="text/css";q.textContent="body.enhancer-for-youtube-wide-player .watch-stage-mode .player-height,body.enhancer-for-youtube-wide-player .watch-stage-mode embed#movie_player,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
e+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-height,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode embed#movie_player,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{height:"+
d+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode .player-width,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+c+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-width,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) video.html5-main-video,body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-iv-video-content{width:"+
b+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-chrome-bottom{width:"+(c-24)+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode #movie_player:not(.ytp-fullscreen) .ytp-chrome-bottom{width:"+(b-24)+"px !important}body.enhancer-for-youtube-wide-player .watch-stage-mode .player-width{left:-"+g+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) .watch-stage-mode .player-width{left:-"+
r+"px !important}body.enhancer-for-youtube-wide-player:not(.enhancer-for-youtube-cinema-mode) #player-playlist .watch-playlist{top:"+l+"px !important}body.enhancer-for-youtube-wide-player.viewport:not(.enhancer-for-youtube-pinned-player) #player-playlist .watch-playlist{top:"+n+"px !important}body.enhancer-for-youtube-cinema-mode:not(.enhancer-for-youtube-wide-player) #player-playlist .watch-playlist{top:-"+p+"px !important}body.enhancer-for-youtube-cinema-mode:not(.enhancer-for-youtube-wide-player) .watch-stage-mode #player-playlist .watch-playlist{top:-360px !important}body.enhancer-for-youtube-wide-player.enhancer-for-youtube-cinema-mode #player-playlist .watch-playlist{top:-"+
m+"px !important}";a.head.appendChild(q);oa=!0},Ka=function(){window.IntersectionObserver&&!m.hasAttribute("io")&&(m.setAttribute("io",1),wa=new IntersectionObserver(function(d){if((0===d[0].intersectionRatio&&!a.body.classList.contains("enhancer-for-youtube-pinned-player")&&0<window.scrollY||0<d[0].intersectionRatio&&.12>d[0].intersectionRatio)&&window.scrollY>m.offsetHeight-100&&T()){a.body.classList.add("enhancer-for-youtube-pinned-player");try{g.style.top=""}catch(h){}0<=b.autofocusevents.indexOf("pin")&&
q()}else 0!==d[0].intersectionRatio&&(a.body.classList.remove("enhancer-for-youtube-pinned-player"),n||Ta())},{threshold:.12}),wa.observe(m))},Ta=function(){setTimeout(function(){try{if(!a.body.classList.contains("enhancer-for-youtube-pinned-player")){var b=window.getComputedStyle(m).height,h=window.getComputedStyle(d).height,c=window.getComputedStyle(g).height;h!==b?(d.style.width=window.getComputedStyle(m).width,d.style.height=b,d.style.width="",d.style.height=""):c!==b&&(g.style.width=window.getComputedStyle(m).width,
g.style.height=b,g.style.top="")}}catch(e){}},50)},Ua=function(){xa=setInterval(function(){try{if("function"!==typeof d.getPlayerState&&N(),0===d.getPlayerState()&&(clearInterval(xa),!k.querySelector("i.loop").parentNode.classList.contains("active"))){var b=a.querySelector(".playlist-videos-container .playlist-videos-list li.currently-playing");if(b){var h=b.nextElementSibling;h&&(a.location.href=h.querySelector("a.playlist-video").href)}}}catch(c){}},5E3)},q=function(){try{a.activeElement.blur(),
d.focus({preventScroll:!0})}catch(f){}},sa=function(){d=a.querySelector("#c4-player")},N=function(){d=a.querySelector("#movie_player")},T=function(){return/^https:\/\/www\.youtube\.com\/watch\?(.*&)?v=/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/c\/.*\/live/.test(a.location.href)},ha=function(a,b){var c=parseInt(a.slice(1),16),d=0>b?0:255,f=0>b?-1*b:b,g=c>>16,h=c>>8&255;c&=255;return"#"+(16777216+65536*(Math.round((d-g)*f)+g)+256*(Math.round((d-h)*f)+h)+(Math.round((d-c)*f)+c)).toString(16).slice(1)},
La=function(){var d=a.createElement("style"),g=b.toolbarbackgroundcolor.replace("#",""),c=parseInt(g.substring(0,2),16),e=parseInt(g.substring(2,4),16);g=parseInt(g.substring(4,6),16);d.type="text/css";d.textContent="#enhancer-for-youtube-toolbar,body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-toolbar-wrapper:hover #enhancer-for-youtube-toolbar{background-color:"+b.toolbarbackgroundcolor+";border-top:0.077em solid "+b.toolbarbordercolor+";border-right:0.077em solid "+b.toolbarbordercolor+
";border-left:0.077em solid "+b.toolbarbordercolor+";color:"+b.toolbarcolor+"}#enhancer-for-youtube-toolbar i{color:"+b.toolbarcolor+" !important}#enhancer-for-youtube-toolbar.transparency{opacity:"+b.toolbaropacity/100+"}#enhancer-for-youtube-slider.ui-widget-content{background-image:none;background-color:"+b.toolbarbackgroundcolor+";border:0.077em solid "+b.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-widget-header{background-image:none;background-color:"+ha(b.toolbarbackgroundcolor,-.1)+
"}#enhancer-for-youtube-slider .ui-state-default{background-image:none;background-color:"+ha(b.toolbarbackgroundcolor,-.1)+";border:0.077em solid "+b.toolbarbordercolor+"}#enhancer-for-youtube-slider .ui-state-hover,#enhancer-for-youtube-slider .ui-state-focus{background-image:none;background-color:"+ha(b.toolbarbackgroundcolor,-.15)+";border:0.077em solid "+ha(b.toolbarbordercolor,-.15)+"}#enhancer-for-youtube-toolbar .start-end{background-color:rgba("+c+","+e+","+g+",0.85)}#enhancer-for-youtube-filters{background-color:"+
b.toolbarbackgroundcolor+" !important;border:0.077em solid "+b.toolbarbordercolor+" !important;color:"+b.toolbarcolor+" !important}#enhancer-for-youtube-unpin-player,#enhancer-for-youtube-filters button.close{color:"+b.toolbarcolor+" !important}";a.head.appendChild(d)},Va=function(){Ma=setInterval(function(){try{(a.activeElement.classList.contains("ytp-progress-bar")||a.activeElement.classList.contains("ytp-volume-panel"))&&q()}catch(f){}},3E3)},Wa=function(){clearInterval(Ma)},Xa=function(a){try{100<=
a&&setTimeout(function(){d.nextVideo()},2E3)}catch(h){}},Na=function(a){1===a&&(d.removeEventListener("onStateChange",Na),g&&b.overridespeeds?g.playbackRate=r:d.setPlaybackRate(r))},Ya=function(a){"number"===typeof a&&(r=a)},Za=function(f){try{b.pausevideos&&!a.hidden&&1===f&&window.postMessage({enhancerforyoutube:"pause-videos"},"*"),b.autopausevideos&&!O&&1===f&&X(),b.selectquality&&!F&&1===f&&ba(),0===f&&"video"===B&&setTimeout(function(){d.classList.contains("ended-mode")&&(z.value=z.max)},500)}catch(h){}},
$a=function(f){try{b.pausevideos&&!a.hidden&&1===f&&window.postMessage({enhancerforyoutube:"pause-videos"},"*");1===f&&ia++;if(b.removeads&&1===f&&3>ia&&0>ja.indexOf(A)||va&&1===f&&3>ia)"video"===B?aa(f):(g.currentTime=g.duration,Z());0===f&&(Y=!1,d.addEventListener("onStateChange",Na),Z())}catch(h){}},U=function(){y||(y=a.createElement("link"),y.rel="stylesheet",y.href=P+"/youtube.css",a.head.appendChild(y),y=a.createElement("style"),y.type="text/css",y.textContent="#enhancer-for-youtube-background{background-color:"+
b.backgroundcolor+"}body.enhancer-for-youtube-cinema-mode #enhancer-for-youtube-background{opacity:"+b.backgroundopacity/100+";visibility:visible}",a.head.appendChild(y),La());B=d=m=g=va=Y=F=!1;ia=0;if(T())if(B="video",N(),d)try{A=d.getVideoData().author}catch(c){(A=a.querySelector(".yt-user-info"))&&(A=A.textContent.trim())}else A="";else if(/^https:\/\/www\.youtube\.com\/channel\/[^\/]+/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/channel\/[^\/]+\/featured/.test(a.location.href)||/^https:\/\/www\.youtube\.com\/user\/[^\/]+/.test(a.location.href)||
/^https:\/\/www\.youtube\.com\/user\/[^\/]+\/featured/.test(a.location.href))if(B="channel",sa(),d)try{A=d.getVideoData().author}catch(c){(A=a.querySelector("h1.branded-page-header-title"))&&(A=A.textContent.trim())}else A="";if(B&&d){m=d.parentNode;"EMBED"===d.nodeName?(n=!0,spf.dispose(),"video"===B&&0<a.location.href.indexOf("list=")&&Ua(),a.body.classList.add("flash-player-loaded")):((g=d.querySelector("video.html5-main-video"))&&g.addEventListener("timeupdate",Ra),d.addEventListener("onAdStateChange",
$a),d.addEventListener("onStateChange",Za),d.addEventListener("onPlaybackRateChange",Ya),d.addEventListener("onError",Xa),m.addEventListener("mouseleave",Wa),m.addEventListener("mouseenter",Va),m.addEventListener("click",Fa),m.addEventListener("wheel",Ha),m.addEventListener("click",Ia),setTimeout(function(){try{g&&b.overridespeeds?(g.playbackRate=r,g.defaultPlaybackRate=r):d.setPlaybackRate(r)}catch(c){}},500));if("video"===B){b.removeads&&0>ja.indexOf(A)&&(n||!n&&1===d.getAdState())?aa():b.autopausevideos&&
(n||!n&&1===d.getPlayerState())?X():b.selectquality&&(n?Q():ba());b.removeads&&0>ja.indexOf(A)&&Z();b.cinemamode?setTimeout(function(){qa();!b.cinemamodewideplayer&&b.wideplayer&&E("large")},b.cinemamodewideplayer||b.wideplayer?1200:1):b.wideplayer&&setTimeout(function(){E("large")},1200);v?(v.style.display="",x.style.display=""):Sa();b.pinnedplayer&&(Ka(),a.body.classList.add(b.pinnedplayersize,b.pinnedplayerposition));if(b.expanddescription){a.body.classList.add("expanded-description");try{a.querySelector("#action-panel-details button.yt-uix-expander-collapsed-body").addEventListener("click",
function(){setTimeout(function(){a.body.classList.remove("expanded-description")},200)})}catch(c){}}if(b.disableautoplay){var f=a.querySelector("input#autoplay-checkbox");if(f&&f.checked)var h=setInterval(function(){f.checked?f.click():clearInterval(h)},500)}0<a.location.href.indexOf("list=")&&setTimeout(function(){try{"block"===window.getComputedStyle(a.querySelector("#player-unavailable"),null).getPropertyValue("display")&&a.querySelector(".playlist-videos-container .playlist-videos-list li.currently-playing").nextElementSibling.querySelector("a.playlist-video").click()}catch(c){}},
2E3)}else"channel"===B&&(b.autopausevideos?X():b.selectquality&&(n?Q():ba()));ta(n?m:d);b.controlvolume&&m.addEventListener("wheel",Ca);b.enablefilters&&g&&(g.style["-webkit-filter"]=b.filter,g.style.filter=b.filter);try{b.defaultvolume&&d.setVolume(b.volume),d[b.removeannotations?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",b.removeannotations?0:1)}catch(c){}b.pausevideos&&!a.hidden&&window.postMessage({enhancerforyoutube:"pause-videos"},"*")}};window.EnhancerForYouTube=
!0;var P=EnhancerForYouTubeResources,b=EnhancerForYouTubePreferences,C=EnhancerForYouTubeMessages,ua=a.hidden,t=a.querySelector("#page"),m,d,g,x,v,k,u,L,Ga,D,Aa,z,M,O,wa,y,Ja,n,oa,fa,B,R,Ma,xa,V,Oa,H,p,w,G,va,ia=0,Y,F,A,ja=""!==b.whitelist?b.whitelist.split(","):[],r=b.speed,ka,S;(new MutationObserver(function(f){f.forEach(function(f){if(null!==f.addedNodes)for(var c=f.addedNodes.length-1;0<=c;c--)if(!n&&f.addedNodes[c].id&&("movie_player"===f.addedNodes[c].id||"c4-player"===f.addedNodes[c].id)){if("EMBED"===
f.addedNodes[c].nodeName){try{d.stopVideo()}catch(e){}m=f.addedNodes[c].parentNode;ta(m);k&&(k.querySelector(".speed").classList.add("not-allowed"),k.querySelector(".filters").classList.add("not-allowed"))}U()}else if("VIDEO"===f.addedNodes[c].nodeName&&g&&g!=d.querySelector("video.html5-main-video"))g=f.addedNodes[c],setTimeout(function(){O=!1;U();try{g&&b.overridespeeds?(g.playbackRate=r,g.defaultPlaybackRate=r):d.setPlaybackRate(r)}catch(e){}},650);else if(f.addedNodes[c].id&&"comment-section-renderer"===
f.addedNodes[c].id&&b.newestcomments&&!ka)setTimeout(function(){try{a.querySelector(".comment-section-sort-menu button.yt-uix-menu-trigger").click()}catch(e){}},200);else if("IFRAME"===f.addedNodes[c].nodeName&&f.addedNodes[c].classList.contains("comment-section-sort-menu-mask")&&b.newestcomments&&!ka)try{a.querySelector('button.comment-section-sort-menu-item[data-menu_name="newest-first"]').click(),ka=!0}catch(e){}})})).observe(a.body,{childList:!0,subtree:!0});window.addEventListener("spfrequest",
function(b){n&&(b.preventDefault(),a.location.href=b.detail.url);clearInterval(xa);clearInterval(R);O=ua=ka=!1;v&&(v.style.display="none",x.style.display="none",D&&(clearInterval(V),k.querySelector("i.loop").parentNode.classList.remove("active"),D.slider("destroy")));a.body.classList.remove("enhancer-for-youtube-pinned-player");try{0>b.detail.url.indexOf("/watch?")&&(da(),E("default")),d.classList.remove("ads-removed")}catch(h){}});window.addEventListener("spfdone",function(a){U()});(a.querySelector("#movie_player")||
a.querySelector("#c4-player"))&&U();a.addEventListener("visibilitychange",function h(){a.hidden||(O||U(),a.removeEventListener("visibilitychange",h),setTimeout(function(){O=!0;ua=!1},1500))});window.addEventListener("load",function c(){window.removeEventListener("load",c);setTimeout(function(){y||U()},250)});b.executescript&&window.postMessage({enhancerforyoutube:"custom-script"},"*");if("default"!==b.theme){var K=a.head.querySelector("#enhancer-for-youtube-theme");K?K.hasAttribute("href")&&0>K.href.indexOf(b.theme)&&
K.setAttribute("href",P+"/vendor/themes/"+b.theme):"custom"===b.theme?window.postMessage({enhancerforyoutube:"custom-theme"},"*"):(K=a.createElement("link"),K.id="enhancer-for-youtube-theme",K.rel="stylesheet",K.href=P+"/vendor/themes/"+b.theme,a.head.appendChild(K))}window.addEventListener("message",function(c){if(c.data.enhancerforyoutube&&"pause-video"===c.data.enhancerforyoutube)try{d.pauseVideo()}catch(l){}else if(c.data.enhancerforyoutube&&"preference-changed"===c.data.enhancerforyoutube){var e=
c.data.value;switch(c.data.name){case "autofocusevents":case "autopausevideos":case "controlvolumealtkey":case "disableautoplay":case "disablepreloading":case "ignoreplaylists":case "newestcomments":case "overridespeeds":case "pauseforegroundtab":case "pausevideos":case "removeads":case "speedvariation":case "toolbartooltips":case "volumevariation":b[c.data.name]=e;break;case "backgroundcolor":b.backgroundcolor=e;x&&(x.style.backgroundColor=e);break;case "backgroundopacity":b.backgroundopacity=e;
x&&(x.style.opacity=e/100);break;case "cinemamode":b.cinemamode=e;T()&&(e?qa():da());break;case "cinemamodewideplayer":b.cinemamodewideplayer=e;T()&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")&&(e?E("large"):E("default"));break;case "controlvolume":b.controlvolume=e;if(m)m[e?"addEventListener":"removeEventListener"]("wheel",Ca);break;case "customtheme":if("default"!==b.theme)try{a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme"))}catch(l){}c=a.createElement("style");
c.type="text/css";c.id="enhancer-for-youtube-theme";c.textContent=e;a.head.appendChild(c);ya(e);break;case "defaultvolume":b.defaultvolume=e;try{e&&d.setVolume(b.volume)}catch(l){}break;case "enablefilters":b.enablefilters=e;try{g.style["-webkit-filter"]=e?b.filter:"",g.style.filter=e?b.filter:""}catch(l){}break;case "executescript":b.executescript=e;b.executescript&&window.postMessage({enhancerforyoutube:"custom-script"},"*");break;case "expanddescription":b.expanddescription=e;try{a.querySelector("#action-panel-details button.yt-uix-expander"+
(e?"-collapsed":"")+"-body").click()}catch(l){}break;case "filter":b.filter=e;if(!a.hidden)try{g.style["-webkit-filter"]=e,g.style.filter=e,k.querySelector("i.filters").parentNode.classList.add("active")}catch(l){}break;case "message":b.message=e;la();break;case "pinnedplayer":b.pinnedplayer=e;m&&m.removeAttribute("io");if(e)a.body.classList.add(b.pinnedplayersize,b.pinnedplayerposition),T()&&Ka();else try{a.body.classList.remove("enhancer-for-youtube-pinned-player",b.pinnedplayersize,b.pinnedplayerposition),
wa.disconnect()}catch(l){}break;case "pinnedplayerposition":a.body.classList.add(e);a.body.classList.remove(b.pinnedplayerposition);b.pinnedplayerposition=e;break;case "pinnedplayersize":a.body.classList.add(e);a.body.classList.remove(b.pinnedplayersize);b.pinnedplayersize=e;break;case "quality1":case "quality2":case "quality3":case "quality4":case "selectquality":b[c.data.name]=e;if("quality1"===c.data.name||b.selectquality)e=(new Date).getTime(),localStorage["yt-player-quality"]='{"data":"'+b.quality1+
'","expiration":'+(e+2592E6)+',"creation":'+e+"}";B&&b.selectquality&&(F=!1,n?Q():ba());break;case "removeannotations":b.removeannotations=e;try{d[e?"unloadModule":"loadModule"]("annotations_module"),d.setAttribute("annotations-module-loaded",e?0:1)}catch(l){}break;case "slideeffect":b.slideeffect=e;if(k)k.classList[e?"add":"remove"]("slide-effect");break;case "speed":b.speed=r=e;try{0>[.25,.5,1,1.25,1.5,2].indexOf(e)?(g.playbackRate=e,g.defaultPlaybackRate=e):d.setPlaybackRate(e)}catch(l){}break;
case "theme":try{if("default"!==b.theme&&a.head.removeChild(a.head.querySelector("#enhancer-for-youtube-theme")),b.theme=e,"custom"===e)window.postMessage({enhancerforyoutube:"custom-theme"},"*");else if("default"!==e){var p=a.createElement("link");p.id="enhancer-for-youtube-theme";p.rel="stylesheet";p.href=P+"/vendor/themes/"+b.theme;a.head.appendChild(p)}}catch(l){}ya();break;case "toolbarbuttons":b.toolbarbuttons=e;k&&la();break;case "toolbarbackgroundcolor":case "toolbarbordercolor":case "toolbarcolor":case "toolbaropacity":b[c.data.name]=
e;La();break;case "transparency":b.transparency=e;if(k)k.classList[e?"add":"remove"]("transparency");break;case "volume":b.volume=e;try{d.setVolume(e)}catch(l){}break;case "whitelist":ja=""!==e?e.split(","):[];break;case "wideplayer":b.wideplayer=e;T()&&(e?E("large"):E("default"));break;case "wideplayerviewport":(b.wideplayerviewport=e,e)?e&&fa&&(a.body.classList.contains("enhancer-for-youtube-wide-player")&&a.body.classList.contains("enhancer-for-youtube-cinema-mode")?a.body.classList.add("_viewport_"):
a.body.classList.contains("enhancer-for-youtube-wide-player")&&(a.body.classList.add("viewport"),setTimeout(function(){window.scrollTo(window.scrollX,d.getBoundingClientRect().top+window.scrollY)},80))):a.body.classList.remove("viewport","_viewport_")}}});window.addEventListener("error",function(b){setTimeout(function(){n||!d||d.querySelector("video")||a.location.reload()},a.documentElement.hasAttribute("flash-player-for-youtube")||a.documentElement.hasAttribute("youtube-flash-player")?3E3:1)});window.addEventListener("resize",
function(a){clearTimeout(Oa);Oa=setTimeout(pa,500)});a.addEventListener("keydown",function(a){27===a.keyCode&&d&&!d.classList.contains("ytp-fullscreen")&&x&&x.click()})}})(document);